# Stage 1: Build the Go application
FROM golang:1.12.5-alpine3.9 AS build

# Install dependencies and setup Go environment
RUN apk update && apk upgrade && apk add --no-cache git dpkg gcc musl-dev

# Set the working directory inside the container
WORKDIR /go/src/work

# Copy Go module files to take advantage of Docker cache
COPY ./src/go.mod ./src/go.sum ./

# Download dependencies using Go modules
RUN go mod tidy

# Copy the rest of the application code
COPY ./src/ .

# Build the Go application
RUN go build -o app .

# Stage 2: Create a small image with the compiled app
FROM alpine:3.9

# Set the working directory in the container
WORKDIR /root/

# Copy the compiled binary from the build stage
COPY --from=build /go/src/work/app .

# Expose the necessary port
EXPOSE 8080

# Run the application
CMD ["./app"]
